/* eslint-disable import/prefer-default-export */
export default () => ({
    microphonesNumber: null,
    filterQuery: '',
    microphones: [
        // {
        //     name: 'Aeumann U47',
        //     manufactor: 'Georg Neumann GmbH',
        //     year: '1901',
        //     technology: 'condenser',
        //     preamp: 'tube',
        //     rating: 1.0,
        //     _id: '44465zrf85jvHz76FTgf1',
        // },
        // {
        //     name: 'Beumann U87',
        //     manufactor: 'Georg Neumann GmbH',
        //     year: '1951',
        //     technology: 'condenser',
        //     preamp: 'tube',
        //     rating: 5.0,
        //     _id: '44465zrf85jvHz76FTgf2',
        // },
        // {
        //     name: 'Ceumann U67',
        //     manufactor: 'Georg Neumann GmbH',
        //     year: '1901',
        //     technology: 'condenser',
        //     preamp: 'tube',
        //     rating: 4.0,
        //     _id: '44465zrf85jvHz76FTgf3',
        // },
        // {
        //     name: 'Eeumann U47',
        //     manufactor: 'Georg Neumann GmbH',
        //     year: '1951',
        //     technology: 'condenser',
        //     preamp: 'tube',
        //     rating: 3.0,
        //     _id: '44465zrf85jvHz76FTgf4',
        // },
        // {
        //     name: 'Beumann U87',
        //     manufactor: 'Georg Neumann GmbH',
        //     year: '1901',
        //     technology: 'condenser',
        //     preamp: 'tube',
        //     rating: 4.0,
        //     _id: '44465zrf85jvHz76FTgf5',
        // },
        // {
        //     name: 'Ceumann U67',
        //     manufactor: 'Georg Neumann GmbH',
        //     year: '1951',
        //     technology: 'condenser',
        //     preamp: 'tube',
        //     rating: 4.0,
        //     _id: '44465zrf85jvHz76FTgf6',
        // },
        // {
        //     name: 'Feumann U47',
        //     manufactor: 'Georg Neumann GmbH',
        //     year: '1951',
        //     technology: 'condenser',
        //     preamp: 'tube',
        //     rating: 2.0,
        //     _id: '44465zrf85jvHz76FTgf7',
        // },
        // {
        //     name: 'Neumann U87',
        //     manufactor: 'Georg Neumann GmbH',
        //     year: '1951',
        //     technology: 'condenser',
        //     preamp: 'tube',
        //     rating: 4.0,
        //     _id: '44465zrf85jvHz76FTgf8',
        // },
        // {
        //     name: 'Geumann U67',
        //     manufactor: 'Georg Neumann GmbH',
        //     year: '1951',
        //     technology: 'condenser',
        //     preamp: 'tube',
        //     rating: 4.0,
        //     _id: '44465zrf85jvHz76FTgf9',
        // },
    ],
});
