/* eslint-disable import/prefer-default-export */
export default () => ({
    microphones: [
        {
            name: 'Neumann U47',
            manufactor: 'Georg Neumann GmbH',
            year: '1901',
            technology: 'condenser',
            preamp: 'tube',
            rating: 1.0,
            _id: '44465zrf85jvHz76FTgf1',
        },
        {
            name: 'Neumann U87',
            manufactor: 'Georg Neumann GmbH',
            year: '1951',
            technology: 'condenser',
            preamp: 'tube',
            rating: 5.0,
            _id: '44465zrf85jvHz76FTgf2',
        },
        {
            name: 'Neumann U67',
            manufactor: 'Georg Neumann GmbH',
            year: '1901',
            technology: 'condenser',
            preamp: 'tube',
            rating: 4.0,
            _id: '44465zrf85jvHz76FTgf3',
        },
        {
            name: 'Neumann U47',
            manufactor: 'Georg Neumann GmbH',
            year: '1951',
            technology: 'condenser',
            preamp: 'tube',
            rating: 3.0,
            _id: '44465zrf85jvHz76FTgf4',
        },
        {
            name: 'Neumann U87',
            manufactor: 'Georg Neumann GmbH',
            year: '1901',
            technology: 'condenser',
            preamp: 'tube',
            rating: 4.0,
            _id: '44465zrf85jvHz76FTgf5',
        },
        {
            name: 'Neumann U67',
            manufactor: 'Georg Neumann GmbH',
            year: '1951',
            technology: 'condenser',
            preamp: 'tube',
            rating: 4.0,
            _id: '44465zrf85jvHz76FTgf6',
        },
        {
            name: 'Neumann U47',
            manufactor: 'Georg Neumann GmbH',
            year: '1951',
            technology: 'condenser',
            preamp: 'tube',
            rating: 2.0,
            _id: '44465zrf85jvHz76FTgf7',
        },
        {
            name: 'Neumann U87',
            manufactor: 'Georg Neumann GmbH',
            year: '1951',
            technology: 'condenser',
            preamp: 'tube',
            rating: 4.0,
            _id: '44465zrf85jvHz76FTgf8',
        },
        {
            name: 'Neumann U67',
            manufactor: 'Georg Neumann GmbH',
            year: '1951',
            technology: 'condenser',
            preamp: 'tube',
            rating: 4.0,
            _id: '44465zrf85jvHz76FTgf9',
        },
    ],
});
